services:
  - type: web
    name: mindful-money-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_NAME
        value: "mindful_money"
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
